# Generated by Django 3.2.8 on 2021-10-09 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_info_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('uid', models.IntegerField(default='null')),
                ('total_member', models.IntegerField()),
                ('age', models.IntegerField()),
                ('first_booking', models.DateField()),
                ('second_booking', models.DateField()),
            ],
            options={
                'db_table': 'member_info_table',
            },
        ),
        migrations.CreateModel(
            name='vaccineBookingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(default='null', max_length=50)),
                ('pincode', models.IntegerField(default='null')),
                ('phone', models.IntegerField()),
                ('first_dose', models.DateField()),
                ('second_dose', models.DateField()),
                ('first_verification', models.BooleanField(default='False')),
                ('second_verification', models.BooleanField(default='False')),
            ],
            options={
                'db_table': 'vaccine_booking_info',
            },
        ),
        migrations.CreateModel(
            name='VaccineSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('pin_code', models.IntegerField(default='null')),
                ('vaccine_12', models.IntegerField(default='null')),
                ('vaccine_18', models.IntegerField(default='null')),
                ('vaccine_45', models.IntegerField(default='null')),
                ('vaccine_60', models.IntegerField(default='null')),
            ],
            options={
                'db_table': 'vaccineslot',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_member', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
